// <auto-generated />
using System;
using System.Collections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StrateZone_Repository.Data;

#nullable disable

namespace StrateZone_Repository.Migrations
{
    [DbContext(typeof(StrateZoneDbContext))]
    [Migration("20250302125718_FixEnums_2")]
    partial class FixEnums_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "course_slot_status", "course_slot_status", new[] { "upcoming", "in_progress", "completed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "course_status", "course_status", new[] { "open", "closed", "in_progress", "completed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "event_status", "event_status", new[] { "upcoming", "ongoing", "completed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "event_type", "event_type", new[] { "tournament", "promotion" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "game_extension", "game_extension", new[] { "bullet", "lightning", "flip", "traditional" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "game_type", "game_type", new[] { "chess", "xiangqi", "go" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "gender", "gender", new[] { "male", "female" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "message_status", "message_status", new[] { "read", "unread" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "order_status", "order_status", new[] { "pending", "shipped", "delivered", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "participant_status", "participant_status", new[] { "enrolled", "drop_out", "in_progress", "completed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "product_status", "product_status", new[] { "available", "out_of_stock", "discontinued" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ranking", "ranking", new[] { "basic", "silver", "gold", "platinum" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "request_status", "request_status", new[] { "pending", "accepted", "rejected", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "room_status", "room_status", new[] { "available", "unavailable", "closed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "room_type", "room_type", new[] { "study", "appointment" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "skill_level", "skill_level", new[] { "beginner", "intermediate", "advanced" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "thread_status", "thread_status", new[] { "published", "rejected", "pending", "deleted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ticket_type", "ticket_type", new[] { "withdrawal", "feedback", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_type", "transaction_type", new[] { "deposit", "withdrawal", "refund" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_course_result", "user_course_result", new[] { "passed", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", "user_role", new[] { "registered_user", "member", "instructor", "staff", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "voucher_status", "voucher_status", new[] { "active", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wallet_status", "wallet_status", new[] { "active", "closed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StrateZone_Repository.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("ScheduleTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("schedule_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("AppointmentId")
                        .HasName("appointments_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cart_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.HasKey("CartId")
                        .HasName("carts_pkey");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("integer")
                        .HasColumnName("cart_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("product_quantity");

                    b.HasKey("Id")
                        .HasName("cart_items_pkey");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasColumnName("rating")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("ReplyTo")
                        .HasColumnType("integer")
                        .HasColumnName("reply_to");

                    b.Property<int?>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId")
                        .HasName("comments_pkey");

                    b.HasIndex("ReplyTo");

                    b.HasIndex("ThreadId");

                    b.HasIndex("UserId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("course_name");

                    b.Property<string>("CourseStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chess_type");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("integer")
                        .HasColumnName("instructor_id");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_level");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("CourseId")
                        .HasName("courses_pkey");

                    b.HasIndex("InstructorId");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.CoursesSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_at");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("integer")
                        .HasColumnName("instructor_id");

                    b.Property<DateTime?>("OnDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("on_date");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("courses_slot_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("RoomId");

                    b.ToTable("courses_slot", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("EventId")
                        .HasName("events_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Friendlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FriendId")
                        .HasColumnType("integer")
                        .HasColumnName("friend_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("friendlists_pkey");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("friendlists", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Friendrequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FromUser")
                        .HasColumnType("integer")
                        .HasColumnName("from_user");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("status");

                    b.Property<int>("ToUser")
                        .HasColumnType("integer")
                        .HasColumnName("to_user");

                    b.HasKey("Id")
                        .HasName("friendrequests_pkey");

                    b.HasIndex("FromUser");

                    b.HasIndex("ToUser");

                    b.ToTable("friendrequests", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.GameExtension", b =>
                {
                    b.Property<int>("ExtensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("extension_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExtensionId"));

                    b.Property<string>("ExtensionName")
                        .IsRequired()
                        .HasColumnType("game_extension")
                        .HasColumnName("extension_name");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.HasKey("ExtensionId")
                        .HasName("gameExtensions_pkey");

                    b.HasIndex("TypeId");

                    b.ToTable("gameExtensions", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.GameType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("game_type")
                        .HasColumnName("type_name");

                    b.HasKey("TypeId")
                        .HasName("gameTypes_pkey");

                    b.ToTable("gameTypes", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url");

                    b.HasKey("ImageId")
                        .HasName("images_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("ThreadId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("likes_pkey");

                    b.HasIndex("CommentId");

                    b.HasIndex("ThreadId");

                    b.HasIndex("UserId");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("integer")
                        .HasColumnName("receiver_id");

                    b.Property<int?>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("MessageId")
                        .HasName("messages_pkey");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TrackingNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(22)
                        .HasColumnType("character varying(22)")
                        .HasColumnName("tracking_number")
                        .HasDefaultValueSql("NULL::character varying");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("integer")
                        .HasColumnName("voucher_id");

                    b.HasKey("OrderId")
                        .HasName("orders_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("order_details_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_details", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("payments_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int?>("GameTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("game_type_id");

                    b.Property<BitArray>("MemberFee")
                        .HasColumnType("bit(1)")
                        .HasColumnName("member_fee");

                    b.Property<decimal?>("Price1")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<BitArray>("TeachingSalary")
                        .HasColumnType("bit(1)")
                        .HasColumnName("teaching_salary");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("prices_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("ProductId");

                    b.ToTable("prices", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<int?>("InventoryCount")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_count");

                    b.Property<string>("ProductName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("ProductId")
                        .HasName("products_pkey");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("product_tags_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("TagId");

                    b.ToTable("product_tags", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("RoomName")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("room_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_type");

                    b.HasKey("RoomId")
                        .HasName("rooms_pkey");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("table_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TableId"));

                    b.Property<decimal?>("Fee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fee");

                    b.Property<int?>("GameExtensionId")
                        .HasColumnType("integer")
                        .HasColumnName("gameExtension_id");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.HasKey("TableId")
                        .HasName("tables_pkey");

                    b.HasIndex("GameExtensionId");

                    b.HasIndex("RoomId");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.TablesAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer")
                        .HasColumnName("table_id");

                    b.HasKey("Id")
                        .HasName("tables_appointments_pkey");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("TableId");

                    b.ToTable("tables_appointments", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tag_name");

                    b.HasKey("TagId")
                        .HasName("tags_pkey");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Thread", b =>
                {
                    b.Property<int>("ThreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ThreadId"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<double?>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasColumnName("rating")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("ThreadId")
                        .HasName("threads_pkey");

                    b.HasIndex("CreatedBy");

                    b.ToTable("threads", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.ThreadsTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.Property<int?>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.HasKey("Id")
                        .HasName("threads_tags_pkey");

                    b.HasIndex("TagId");

                    b.HasIndex("ThreadId");

                    b.ToTable("threads_tags", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attachment_url");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int?>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_type");

                    b.HasKey("Id")
                        .HasName("tickets_pkey");

                    b.HasIndex("SenderId");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("OfUser")
                        .HasColumnType("integer")
                        .HasColumnName("of_user");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("transactions_pkey");

                    b.HasIndex("OfUser");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<int?>("CartId")
                        .HasColumnType("integer")
                        .HasColumnName("cart_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<int?>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("points");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasComment("Depends on Role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("CartId");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "users_phone_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.UsersCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("EnrolledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<int?>("ParticipantStatus")
                        .HasColumnType("integer")
                        .HasColumnName("participant_status");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("users_courses_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("users_courses", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("voucher_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VoucherId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("ExpireDate")
                        .HasColumnType("date")
                        .HasColumnName("expire_date");

                    b.Property<decimal?>("MinPriceCondition")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("min_price_condition")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("VoucherName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("voucher_name");

                    b.HasKey("VoucherId")
                        .HasName("vouchers_pkey");

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wallet_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WalletId"));

                    b.Property<decimal?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("balance")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("WalletId")
                        .HasName("wallet_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("wallet", (string)null);
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Appointment", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("appointments_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.CartItem", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .HasConstraintName("cart_items_cart_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("cart_items_product_id_fkey");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Comment", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Comment", "ReplyToNavigation")
                        .WithMany("InverseReplyToNavigation")
                        .HasForeignKey("ReplyTo")
                        .HasConstraintName("comments_reply_to_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Thread", "Thread")
                        .WithMany("Comments")
                        .HasForeignKey("ThreadId")
                        .HasConstraintName("comments_thread_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("comments_user_id_fkey");

                    b.Navigation("ReplyToNavigation");

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Course", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.User", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("courses_instructor_id_fkey");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.CoursesSlot", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Course", "Course")
                        .WithMany("CoursesSlots")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("courses_slot_course_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.User", "Instructor")
                        .WithMany("CoursesSlots")
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("courses_slot_instructor_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Room", "Room")
                        .WithMany("CoursesSlots")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("courses_slot_room_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Event", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .HasConstraintName("events_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Friendlist", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.User", "Friend")
                        .WithMany("FriendlistFriends")
                        .HasForeignKey("FriendId")
                        .HasConstraintName("friendlists_friend_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.User", "User")
                        .WithMany("FriendlistUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("friendlists_user_id_fkey");

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Friendrequest", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.User", "FromUserNavigation")
                        .WithMany("FriendrequestFromUserNavigations")
                        .HasForeignKey("FromUser")
                        .IsRequired()
                        .HasConstraintName("friendrequests_from_user_fkey");

                    b.HasOne("StrateZone_Repository.Entities.User", "ToUserNavigation")
                        .WithMany("FriendrequestToUserNavigations")
                        .HasForeignKey("ToUser")
                        .IsRequired()
                        .HasConstraintName("friendrequests_to_user_fkey");

                    b.Navigation("FromUserNavigation");

                    b.Navigation("ToUserNavigation");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.GameExtension", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.GameType", "Type")
                        .WithMany("GameExtensions")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("gameExtensions_type_id_fkey");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Image", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("images_product_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Thread", "Thread")
                        .WithMany("Images")
                        .HasForeignKey("ThreadId")
                        .HasConstraintName("images_thread_id_fkey");

                    b.Navigation("Product");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Like", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("likes_comment_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Thread", "Thread")
                        .WithMany("Likes")
                        .HasForeignKey("ThreadId")
                        .HasConstraintName("likes_thread_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("likes_user_id_fkey");

                    b.Navigation("Comment");

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Message", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.User", "Receiver")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("messages_receiver_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("messages_sender_id_fkey");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Order", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("orders_user_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Voucher", "Voucher")
                        .WithMany("Orders")
                        .HasForeignKey("VoucherId")
                        .HasConstraintName("orders_voucher_id_fkey");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.OrderDetail", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("order_details_order_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("order_details_product_id_fkey");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Payment", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("payments_order_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("payments_user_id_fkey");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Price", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Course", "Course")
                        .WithMany("Prices")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("prices_course_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.GameType", "GameType")
                        .WithMany("Prices")
                        .HasForeignKey("GameTypeId")
                        .HasConstraintName("prices_game_type_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("prices_product_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("GameType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.ProductTag", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("product_tags_product_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .HasConstraintName("product_tags_tag_id_fkey");

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Table", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.GameExtension", "GameExtension")
                        .WithMany("Tables")
                        .HasForeignKey("GameExtensionId")
                        .HasConstraintName("tables_gameExtension_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Room", "Room")
                        .WithMany("Tables")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("tables_room_id_fkey");

                    b.Navigation("GameExtension");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.TablesAppointment", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Appointment", "Appointment")
                        .WithMany("TablesAppointments")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("tables_appointments_appointment_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Table", "Table")
                        .WithMany("TablesAppointments")
                        .HasForeignKey("TableId")
                        .HasConstraintName("tables_appointments_table_id_fkey");

                    b.Navigation("Appointment");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Thread", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.User", "CreatedByNavigation")
                        .WithMany("Threads")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("threads_created_by_fkey");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.ThreadsTag", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Tag", "Tag")
                        .WithMany("ThreadsTags")
                        .HasForeignKey("TagId")
                        .HasConstraintName("threads_tags_tag_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.Thread", "Thread")
                        .WithMany("ThreadsTags")
                        .HasForeignKey("ThreadId")
                        .HasConstraintName("threads_tags_thread_id_fkey");

                    b.Navigation("Tag");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Ticket", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.User", "Sender")
                        .WithMany("Tickets")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("tickets_sender_id_fkey");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Transaction", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.User", "OfUserNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("OfUser")
                        .HasConstraintName("transactions_of_user_fkey");

                    b.Navigation("OfUserNavigation");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.User", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Cart", "Cart")
                        .WithMany("Users")
                        .HasForeignKey("CartId")
                        .HasConstraintName("users_cart_id_fkey");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.UsersCourse", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.Course", "Course")
                        .WithMany("UsersCourses")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("users_courses_course_id_fkey");

                    b.HasOne("StrateZone_Repository.Entities.User", "User")
                        .WithMany("UsersCourses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("users_courses_user_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Wallet", b =>
                {
                    b.HasOne("StrateZone_Repository.Entities.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .HasConstraintName("wallet_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Appointment", b =>
                {
                    b.Navigation("TablesAppointments");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Comment", b =>
                {
                    b.Navigation("InverseReplyToNavigation");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Course", b =>
                {
                    b.Navigation("CoursesSlots");

                    b.Navigation("Prices");

                    b.Navigation("UsersCourses");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.GameExtension", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.GameType", b =>
                {
                    b.Navigation("GameExtensions");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Images");

                    b.Navigation("OrderDetails");

                    b.Navigation("Prices");

                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Room", b =>
                {
                    b.Navigation("CoursesSlots");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Table", b =>
                {
                    b.Navigation("TablesAppointments");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Tag", b =>
                {
                    b.Navigation("ProductTags");

                    b.Navigation("ThreadsTags");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Thread", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("Likes");

                    b.Navigation("ThreadsTags");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Comments");

                    b.Navigation("Courses");

                    b.Navigation("CoursesSlots");

                    b.Navigation("Events");

                    b.Navigation("FriendlistFriends");

                    b.Navigation("FriendlistUsers");

                    b.Navigation("FriendrequestFromUserNavigations");

                    b.Navigation("FriendrequestToUserNavigations");

                    b.Navigation("Likes");

                    b.Navigation("MessageReceivers");

                    b.Navigation("MessageSenders");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Threads");

                    b.Navigation("Tickets");

                    b.Navigation("Transactions");

                    b.Navigation("UsersCourses");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("StrateZone_Repository.Entities.Voucher", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
